# Generated by Django 3.1 on 2020-08-17 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_insurer_compulsory_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurercompulsorypackage',
            name='insurance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rel_insurance_compul_pack', to='insurance.insurance'),
            preserve_default=False,
        ),
    ]
