# Generated by Django 3.1 on 2020-09-02 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_remove_insurance_insurers'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='insurance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='insurers_insurance', to='insurance.insurance'),
            preserve_default=False,
        ),
    ]
