# Generated by Django 3.1 on 2020-09-02 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_insurer_insurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariffication',
            name='code',
        ),
        migrations.RemoveField(
            model_name='tariffication',
            name='parent',
        ),
        migrations.CreateModel(
            name='Personification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=180)),
                ('first_name', models.CharField(max_length=180)),
                ('patronymic', models.CharField(max_length=180)),
                ('iin', models.IntegerField(null=True)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personifications_insurer', to='insurance.insurer')),
            ],
            options={
                'db_table': 'personifications',
            },
        ),
    ]
