# Generated by Django 3.1 on 2020-09-02 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_auto_20200902_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='personification',
            name='compulsory_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personifications_compulsory_package', to='insurance.compulsorypackage'),
        ),
    ]
