# Generated by Django 3.1 on 2020-09-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0010_auto_20200914_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurer',
            name='tariffications',
            field=models.ManyToManyField(null=True, related_name='insurer_tariffication', through='insurance.InsuranceTariffication', to='insurance.Tariffication'),
        ),
    ]
