# Generated by Django 3.1 on 2020-09-14 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0011_auto_20200914_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='drugs',
        ),
        migrations.RemoveField(
            model_name='insurancedrug',
            name='insurance',
        ),
        migrations.AddField(
            model_name='insurancedrug',
            name='insurer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='insur_drug_insurer', to='insurance.insurer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurer',
            name='drugs',
            field=models.ManyToManyField(related_name='insurance_drug', through='insurance.InsuranceDrug', to='insurance.Drug'),
        ),
        migrations.AlterField(
            model_name='insurancetariffication',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insur_tarif_insurer', to='insurance.insurer'),
        ),
    ]
