# Generated by Django 3.1 on 2020-09-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0013_auto_20200919_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurer',
            name='insurance',
        ),
        migrations.AddField(
            model_name='insurance',
            name='insurers',
            field=models.ManyToManyField(related_name='insurances_insurers', to='insurance.Insurer'),
        ),
    ]
