# Generated by Django 3.1 on 2020-10-05 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0014_auto_20200928_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('bin', models.CharField(max_length=12, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=70, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_bank', to='insurance.bank')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_city', to='insurance.city')),
            ],
            options={
                'db_table': 'hospitals',
            },
        ),
        migrations.AddField(
            model_name='insurance',
            name='hospitals',
            field=models.ManyToManyField(related_name='insurances_hospitals', to='insurance.Hospital'),
        ),
    ]
