# Generated by Django 3.1 on 2020-10-05 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0015_auto_20201005_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_bank', to='insurance.bank'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_bank', to='insurance.bank'),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurer_bank', to='insurance.bank'),
        ),
    ]
