# Generated by Django 3.1 on 2020-10-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0018_harm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Harm',
        ),
    ]
