# Generated by Django 3.1 on 2020-12-01 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0019_delete_harm'),
    ]

    operations = [
        migrations.AddField(
            model_name='personification',
            name='gender',
            field=models.CharField(choices=[('M', 'женщина'), ('F', 'мужчина')], default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personification',
            name='profession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profession', to='insurance.profession'),
            preserve_default=False,
        ),
    ]
