# Generated by Django 3.1 on 2020-12-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0020_auto_20201201_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='personification',
            name='birthDate',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
    ]
