# Generated by Django 3.1 on 2020-12-02 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0021_personification_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personification',
            name='birthDate',
        ),
    ]
