# Generated by Django 3.1 on 2020-12-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0022_remove_personification_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='hospitals',
            field=models.ManyToManyField(related_name='insurer_hospitals', to='insurance.Hospital'),
        ),
    ]
