# Generated by Django 3.1 on 2020-12-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0023_insurer_hospitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='profession',
            field=models.ManyToManyField(related_name='insurances_profession', to='insurance.Profession'),
        ),
    ]
