# Generated by Django 3.1 on 2020-12-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0025_profile_insurer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='insurer',
            new_name='insurers',
        ),
    ]
