# Generated by Django 3.1 on 2020-12-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0026_auto_20201206_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='insurers',
        ),
    ]
