# Generated by Django 3.1 on 2020-09-24 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0013_auto_20200919_0608'),
        ('tariffication', '0003_auto_20200924_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='insurance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_insurance', to='insurance.insurance'),
        ),
    ]
