# Generated by Django 3.1 on 2020-09-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariffication', '0007_auto_20200930_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariffication',
            old_name='object_copy',
            new_name='copied',
        ),
    ]
