# Generated by Django 3.1 on 2020-10-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffication', '0011_auto_20201005_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffication',
            name='type',
            field=models.IntegerField(choices=[(1, 'обычный'), (2, 'ОМО'), (3, 'ОПМО')], default=1),
        ),
    ]
