# Generated by Django 3.1 on 2020-10-09 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0019_delete_harm'),
        ('tariffication', '0012_tariffication_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffication',
            name='copied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_copy', to='tariffication.tariffication'),
        ),
        migrations.AlterField(
            model_name='tariffication',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariffications_insurance', to='insurance.insurance'),
        ),
        migrations.AlterField(
            model_name='tariffication',
            name='insurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariffications_insurer', to='insurance.insurer'),
        ),
    ]
