# Generated by Django 3.1 on 2020-10-09 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariffication', '0013_auto_20201009_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffication',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tariffication.tariffication'),
        ),
    ]
