# Generated by Django 3.1 on 2020-10-13 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariffication', '0015_regiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariffication.harm')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariffication.service')),
            ],
            options={
                'db_table': 'service_harm',
            },
        ),
        migrations.AddField(
            model_name='harm',
            name='services',
            field=models.ManyToManyField(through='tariffication.ServiceHarm', to='tariffication.Service'),
        ),
    ]
