# Generated by Django 3.1 on 2020-10-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariffication', '0016_auto_20201013_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRegiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariffication.regiment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariffication.service')),
            ],
            options={
                'db_table': 'service_regiment',
            },
        ),
        migrations.AddField(
            model_name='regiment',
            name='services',
            field=models.ManyToManyField(through='tariffication.ServiceRegiment', to='tariffication.Service'),
        ),
    ]
