# Generated by Django 3.1 on 2020-10-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffication', '0017_auto_20201013_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceregiment',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
