# Generated by Django 3.1 on 2020-10-19 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0019_delete_harm'),
        ('tariffication', '0018_serviceregiment_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceregiment',
            name='insurer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.insurer'),
        ),
    ]
