# Generated by Django 3.1 on 2020-10-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariffication', '0019_serviceregiment_insurer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceregiment',
            name='is_required',
        ),
    ]
