# Generated by Django 3.1 on 2020-10-20 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0019_delete_harm'),
        ('tariffication', '0020_remove_serviceregiment_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceharm',
            name='insurance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_harm_insurances', to='insurance.insurance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceharm',
            name='insurer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.insurer'),
        ),
        migrations.AddField(
            model_name='serviceregiment',
            name='insurance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_regiment_insurances', to='insurance.insurance'),
            preserve_default=False,
        ),
    ]
