# Generated by Django 3.1 on 2020-12-06 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0027_remove_profile_insurers'),
        ('tariffication', '0022_auto_20201202_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='insurer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurer_insurer', to='insurance.insurer'),
        ),
    ]
