# Generated by Django 3.1 on 2020-12-06 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariffication', '0023_service_insurer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='insurer',
        ),
    ]
