# Generated by Django 3.1 on 2020-12-07 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0027_remove_profile_insurers'),
        ('tariffication', '0024_remove_service_insurer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffication',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariffications_hospital', to='insurance.hospital'),
        ),
    ]
