# Generated by Django 3.1 on 2020-12-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariffication', '0025_tariffication_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffication',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_search', to='tariffication.service'),
        ),
    ]
