# Generated by Django 3.1 on 2020-10-05 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0014_auto_20200928_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('code', models.CharField(max_length=80, null=True)),
                ('insurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugs_insurance', to='insurance.insurance')),
            ],
            options={
                'db_table': 'drugs',
            },
        ),
    ]
