from django.urls import path
from . import views
app_name = 'insurance'
urlpatterns = [
    path('', views.InsurerListView.as_view(), name='insurer_list'),
    path('<int:insurer>',
         views.InsurerListView.as_view(), name='insurer_list'),
    path('personification/',
         views.PersonificationListView.as_view(), name='personification_list'),
    path('<int:insurer>/personification/',
         views.PersonificationListView.as_view(), name='personification_list'),
    path('<int:insurer>/personification/create/',
         views.PersonificationCreateView.as_view(),
         name='personification_create'),
    path('<int:insurer>/personification/update/<int:pk>',
         views.PersonificationUpdateView.as_view(),
         name='personification_update'),
    path('<int:insurer>/personification/delete/<int:pk>',
         views.PersonificationDeleteView.as_view(),
         name='personification_delete'),
    path('hospital/list/',
         views.HospitalListView.as_view(), name='hospital_list'),
    path('hospital/create/',
         views.HospitalCreateView.as_view(), name='hospital_create'),
    path('hospital/update/<int:pk>',
         views.HospitalUpdateView.as_view(), name='hospital_update'),
    path('hospital/delete/<int:pk>',
         views.HospitalDeleteView.as_view(), name='hospital_delete'),
    path('profession/list/',
         views.ProfessionListView.as_view(), name='profession_list'),
    path('profession/create/',
         views.ProfessionCreateView.as_view(), name='profession_create'),
    path('profession/update/<int:pk>',
         views.ProfessionUpdateView.as_view(), name='profession_update'),
    path('profession/delete/<int:pk>',
         views.ProfessionDeleteView.as_view(), name='profession_delete'),
]
