# Generated by Django 3.1 on 2020-10-05 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0019_delete_harm'),
        ('prof_med_exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionHarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harm_rel', to='prof_med_exam.harm')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_rel', to='insurance.insurance')),
                ('insurer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurer_rel', to='insurance.insurer')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession_rel', to='insurance.profession')),
            ],
        ),
        migrations.AddField(
            model_name='harm',
            name='professions',
            field=models.ManyToManyField(through='prof_med_exam.ProfessionHarm', to='insurance.Profession'),
        ),
    ]
