# Generated by Django 3.1 on 2020-10-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof_med_exam', '0002_auto_20201005_1239'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='professionharm',
            table='profession_harm',
        ),
    ]
