from django.urls import path
from . import views
app_name = 'tariffication'
urlpatterns = [
    path('list/',
         views.TarifficationListView.as_view(), name='tariffication_list'),
    path('list/<int:parent>', views.TarifficationListView.as_view(),
         name='tariffication_list'),
    path('list/<int:insurer>', views.TarifficationListView.as_view(),
         name='tariffication_list'),
    path('ajax/', views.TarifficationAjaxView.as_view(),
         name='tariffication_ajax'),
    path('ajax/<int:parent>', views.TarifficationAjaxView.as_view(),
         name='tariffication_ajax'),
    path('ajax/update', views.TarifficationAjaxUpdateView.as_view(),
         name='tariffication_ajax_update'),
    path('service/group/create/', views.ServiceGroupCreateView.as_view(),
         name='service_group_create'),
    path('service/group/create/<int:parent>',
         views.ServiceGroupCreateView.as_view(), name='service_group_create'),
    path('service/group/create/<int:insurer>',
         views.ServiceGroupCreateView.as_view(), name='service_group_create'),
    path('service/list/', views.ServiceListView.as_view(),
         name='service_list'),
    path('service/ajax/', views.ServiceAjaxView.as_view(),
         name='service_ajax'),
    path('service/ajax/<int:parent>',
         views.ServiceAjaxView.as_view(), name='service_ajax'),
    path('service/ajax/<int:insurer>',
         views.ServiceAjaxView.as_view(), name='service_ajax'),
    path('service/create/', views.ServiceCreateView.as_view(),
         name='service_create'),
    path('service/update/<int:pk>',
         views.ServiceUpdateView.as_view(), name='service_update'),
    path('service/delete/<int:pk>',
         views.ServiceDeleteView.as_view(), name='service_delete'),
    path('harm/list/', views.HarmListView.as_view(), name='harm_list'),
    path('harm/create/', views.HarmCreateView.as_view(), name='harm_create'),
    path('harm/update/<int:pk>', views.HarmUpdateView.as_view(),
         name='harm_update'),
    path('harm/delete/<int:pk>', views.HarmDeleteView.as_view(),
         name='harm_delete'),
    path('harm/update/<int:pk>', views.HarmUpdateView.as_view(),
         name='harm_update'),
    path('compulsory/package/<int:parent>',
         views.CompulsoryPackage.as_view(), name='compulsory_package_list'),
    path('compulsory/package/<int:parent>/<int:regiment>',
         views.CompulsoryPackage.as_view(), name='compulsory_package_list'),
    path('compulsory/profession/package/<int:parent>',
         views.CompulsoryProfessionPackage.as_view(),
         name='compulsory_profession_package'),
    path('compulsory/profession/package/<int:parent>/<int:harm>',
         views.CompulsoryProfessionPackage.as_view(),
         name='compulsory_profession_package'),
]
